language: node_js
sudo: false
node_js:
   - "6"
   - "4"
notifications:
   irc:
      channels: "chat.freenode.net#laxarjs"
      template:
         - "%{repository_slug} (%{commit}) [%{branch}]: %{message}"
      use_notice: true
branches:
   except:
      - /^feature\/.*$/
